# Generated by Django 5.2.7 on 2025-10-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("vision", models.CharField(blank=True, max_length=50, null=True)),
                ("weapon", models.CharField(blank=True, max_length=50, null=True)),
                ("nation", models.CharField(blank=True, max_length=50, null=True)),
                ("rarity", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
            ],
        ),
    ]
